steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_OAUTH_PROVIDER=${_VITE_OAUTH_PROVIDER}'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tebakinaja:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tebakinaja:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tebakinaja'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tebakinaja:latest'
      - '--region'
      - 'asia-southeast1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'